using System;
using System.Collections.Generic;

namespace BIWebApp.Data
{
    public partial class BI_View_MSP_EpmProject_UserView : BaseEntity
    {
        public System.Guid ProjectOwnerResourceUID { get; set; }
        public System.Guid ProjectUID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectAuthorName { get; set; }
        public Nullable<System.Guid> EnterpriseProjectTypeUID { get; set; }
        public Nullable<System.DateTime> ProjectStartDate { get; set; }
        public Nullable<System.DateTime> ProjectFinishDate { get; set; }
        public Nullable<System.DateTime> ProjectStatusDate { get; set; }
        public string ProjectManagerName { get; set; }
        public int ProjectType { get; set; }
        public string ProjectWorkspaceInternalHRef { get; set; }
        public bool ProjectWbsIsStale { get; set; }
        public bool ProjectEarnedValueIsStale { get; set; }
        public bool ProjectRollupsAreStale { get; set; }
        public bool ProjectHierarchyNotSynchronized { get; set; }
        public bool ProjectCalculationsAreStale { get; set; }
        public bool ProjectGhostTaskAreStale { get; set; }
        public string ProjectCurrency { get; set; }
        public string ProjectCategoryName { get; set; }
        public string ProjectCompanyName { get; set; }
        public string ProjectKeywords { get; set; }
        public string ProjectSubject { get; set; }
        public string ProjectTitle { get; set; }
        public Nullable<short> ResourcePlanUtilizationType { get; set; }
        public Nullable<System.DateTime> ResourcePlanUtilizationDate { get; set; }
        public int ProjectCreatedRevisionCounter { get; set; }
        public int ProjectModifiedRevisionCounter { get; set; }
        public System.DateTime ProjectCreatedDate { get; set; }
        public System.DateTime ProjectModifiedDate { get; set; }
        public Nullable<int> ProjectCalendarDuration { get; set; }
        public bool ProjectVisibilityMode { get; set; }
        public Nullable<System.Guid> ParentProjectUID { get; set; }
        public Nullable<decimal> ProjectFixedCost { get; set; }
        public Nullable<decimal> ProjectCost { get; set; }
        public Nullable<decimal> ProjectOvertimeCost { get; set; }
        public Nullable<decimal> ProjectActualCost { get; set; }
        public Nullable<decimal> ProjectActualOvertimeCost { get; set; }
        public Nullable<decimal> ProjectWork { get; set; }
        public Nullable<decimal> ProjectOvertimeWork { get; set; }
        public Nullable<decimal> ProjectActualWork { get; set; }
        public Nullable<decimal> ProjectActualOvertimeWork { get; set; }
        public Nullable<decimal> ProjectDurationVariance { get; set; }
        public Nullable<decimal> ProjectStartVariance { get; set; }
        public Nullable<decimal> ProjectFinishVariance { get; set; }
        public Nullable<decimal> ProjectDuration { get; set; }
        public Nullable<decimal> ProjectActualDuration { get; set; }
        public Nullable<System.DateTime> ProjectActualStartDate { get; set; }
        public Nullable<System.DateTime> ProjectActualFinishDate { get; set; }
        public Nullable<short> ProjectPercentCompleted { get; set; }
        public Nullable<short> ProjectPercentWorkCompleted { get; set; }
        public Nullable<decimal> ProjectACWP { get; set; }
        public Nullable<decimal> ProjectBCWP { get; set; }
        public Nullable<decimal> ProjectBCWS { get; set; }
        public Nullable<decimal> ProjectSPI { get; set; }
        public Nullable<decimal> ProjectTCPI { get; set; }
        public Nullable<decimal> ProjectVAC { get; set; }
        public Nullable<decimal> ProjectEAC { get; set; }
        public Nullable<decimal> ProjectCostVariance { get; set; }
        public Nullable<decimal> ProjectCV { get; set; }
        public Nullable<decimal> ProjectCPI { get; set; }
        public Nullable<System.DateTime> ProjectEarlyFinish { get; set; }
        public Nullable<System.DateTime> ProjectEarlyStart { get; set; }
        public Nullable<System.DateTime> ProjectLateFinish { get; set; }
        public Nullable<System.DateTime> ProjectLateStart { get; set; }
        public Nullable<decimal> ProjectSV { get; set; }
        public Nullable<decimal> ProjectWorkVariance { get; set; }
        public Nullable<decimal> ProjectBudgetCost { get; set; }
        public Nullable<decimal> ProjectBudgetWork { get; set; }
        public Nullable<decimal> ProjectResourcePlanWork { get; set; }
        public Nullable<decimal> ProjectRegularCost { get; set; }
        public Nullable<decimal> ProjectRemainingCost { get; set; }
        public Nullable<decimal> ProjectRemainingOvertimeCost { get; set; }
        public Nullable<decimal> ProjectActualRegularCost { get; set; }
        public Nullable<decimal> ProjectRemainingRegularCost { get; set; }
        public Nullable<decimal> ProjectRegularWork { get; set; }
        public Nullable<decimal> ProjectRemainingWork { get; set; }
        public Nullable<decimal> ProjectRemainingOvertimeWork { get; set; }
        public Nullable<decimal> ProjectActualRegularWork { get; set; }
        public Nullable<decimal> ProjectRemainingRegularWork { get; set; }
        public Nullable<decimal> ProjectRemainingDuration { get; set; }
        public Nullable<decimal> ProjectCVP { get; set; }
        public Nullable<decimal> ProjectSVP { get; set; }
        public string ProjectOwnerName { get; set; }
        public int ProjectCount { get; set; }
        public Nullable<decimal> ProjectBaseline0Cost { get; set; }
        public Nullable<decimal> ProjectBaseline0FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline0Work { get; set; }
        public Nullable<decimal> ProjectBaseline0BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline0BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline0StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline0FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline0Duration { get; set; }
        public Nullable<decimal> ProjectBaseline1Cost { get; set; }
        public Nullable<decimal> ProjectBaseline1FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline1Work { get; set; }
        public Nullable<decimal> ProjectBaseline1BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline1BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline1StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline1FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline1Duration { get; set; }
        public Nullable<decimal> ProjectBaseline2Cost { get; set; }
        public Nullable<decimal> ProjectBaseline2FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline2Work { get; set; }
        public Nullable<decimal> ProjectBaseline2BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline2BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline2StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline2FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline2Duration { get; set; }
        public Nullable<decimal> ProjectBaseline3Cost { get; set; }
        public Nullable<decimal> ProjectBaseline3FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline3Work { get; set; }
        public Nullable<decimal> ProjectBaseline3BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline3BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline3StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline3FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline3Duration { get; set; }
        public Nullable<decimal> ProjectBaseline4Cost { get; set; }
        public Nullable<decimal> ProjectBaseline4FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline4Work { get; set; }
        public Nullable<decimal> ProjectBaseline4BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline4BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline4StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline4FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline4Duration { get; set; }
        public Nullable<decimal> ProjectBaseline5Cost { get; set; }
        public Nullable<decimal> ProjectBaseline5FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline5Work { get; set; }
        public Nullable<decimal> ProjectBaseline5BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline5BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline5StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline5FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline5Duration { get; set; }
        public Nullable<decimal> ProjectBaseline6Cost { get; set; }
        public Nullable<decimal> ProjectBaseline6FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline6Work { get; set; }
        public Nullable<decimal> ProjectBaseline6BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline6BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline6StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline6FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline6Duration { get; set; }
        public Nullable<decimal> ProjectBaseline7Cost { get; set; }
        public Nullable<decimal> ProjectBaseline7FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline7Work { get; set; }
        public Nullable<decimal> ProjectBaseline7BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline7BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline7StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline7FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline7Duration { get; set; }
        public Nullable<decimal> ProjectBaseline8Cost { get; set; }
        public Nullable<decimal> ProjectBaseline8FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline8Work { get; set; }
        public Nullable<decimal> ProjectBaseline8BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline8BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline8StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline8FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline8Duration { get; set; }
        public Nullable<decimal> ProjectBaseline9Cost { get; set; }
        public Nullable<decimal> ProjectBaseline9FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline9Work { get; set; }
        public Nullable<decimal> ProjectBaseline9BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline9BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline9StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline9FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline9Duration { get; set; }
        public Nullable<decimal> ProjectBaseline10Cost { get; set; }
        public Nullable<decimal> ProjectBaseline10FixedCost { get; set; }
        public Nullable<decimal> ProjectBaseline10Work { get; set; }
        public Nullable<decimal> ProjectBaseline10BudgetCost { get; set; }
        public Nullable<decimal> ProjectBaseline10BudgetWork { get; set; }
        public Nullable<System.DateTime> ProjectBaseline10StartDate { get; set; }
        public Nullable<System.DateTime> ProjectBaseline10FinishDate { get; set; }
        public Nullable<decimal> ProjectBaseline10Duration { get; set; }
        public string Project_Departments { get; set; }
        public string Job_Number { get; set; }
        public string Portfolio_Manager { get; set; }
        public string Programme_Manager { get; set; }
        public string Customer_Name { get; set; }
        public string Project_Status { get; set; }
        public string Cost_Centre { get; set; }
        public string Plan_Type { get; set; }
        public string Chargeable_Project { get; set; }
        public decimal Day_Rate { get; set; }
        public Nullable<decimal> Cost_Rate { get; set; }
    }
}
